#!/bin/sh

if [ -f /usr/share/java/weka.jar ]
then
    jar=/usr/share/java/weka.jar
elif [ -z "${1}" ]
then
    echo "Usage: make-models <weka-jar-location>" >&2
    exit 1
else
    jar="${1}"
fi
mkdir -p target
java -cp "${jar}" weka.classifiers.functions.SimpleLogistic -l model/three_class_SimpleLogistic.model -T arff/test_data.arff -i > target/test_three_class_SimpleLogistic.out
java -cp "${jar}" weka.classifiers.functions.SimpleLogistic -l model/two_class_SimpleLogistic.model -T arff/test_data_binary.arff -i > target/test_two_class_SimpleLogistic.out
